services:
  mysql:
    image: mysql
    container_name: mysql
    ports:
      - 3308:3306
    environment:
       MYSQL_ROOT_PASSWORD: 123456
       MYSQL_DATABASE: cinema
    networks:
      - cinema
    volumes:
      - db_data:/var/lib/mysql


  cinema:
    build: .
    container_name: cinema
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3308/cinema
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
    ports:
      - 8080:8080
    networks:
      - cinema

volumes:
  db_data:

networks:
  cinema:
    driver: bridge